name: SSH Python Restart

on:
  push:
    branches: [main]

jobs:
  start:
    name: Run
    runs-on: ubuntu-latest
    steps:
      - name: Execute remote commands
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script: cd ~/berlockbot; ls; pkill -9 -f "python" > /dev/null 2>&1; git pull; source venv/bin/activate; python berlock_bot.py &
